# 🔥 ARBI PHOENIX - Configuration File
# "The Phoenix configuration that never burns"

# Broker Configuration
broker:
  name: "IC_Markets"  # Change to your broker
  api_type: "MT5"     # MT5, MT4, cTrader, IB, Oanda, FXCM
  server: "ICMarkets-Demo"
  login: "your_login_here"
  password: "your_password_here"
  timeout: 30
  retries: 3
  
  # Order Execution Settings
  default_fill_mode: "IOC"        # IOC, FOK, MARKET, INSTANT, GTC, DAY
  max_deviation: 10               # Maximum price deviation (points)
  execution_timeout: 5.0          # Order execution timeout (seconds)
  retry_attempts: 3               # Number of retry attempts
  retry_delay: 0.1                # Delay between retries (seconds)

# Trading Configuration
trading:
  # Arbitrage Settings
  min_arbitrage_profit: 5      # Minimum profit in pips
  max_spread_cost: 8           # Maximum total spread cost
  min_liquidity: 1.0           # Minimum lot size available
  
  # Position Management
  base_lot_size: 0.01          # Base position size (legacy)
  max_position_risk: 2.0       # Max risk per trade (%)
  max_total_exposure: 20.0     # Max total exposure (%)
  
  # Position Sizing Method
  position_sizing:
    method: "balanced_exposure"     # balanced_exposure, fixed_lot, risk_based
    target_exposure_per_leg: 10000  # USD per triangle leg
    balance_tolerance: 0.05         # 5% deviation allowed
    auto_adjust_exposure: true      # Adjust based on account balance
    
  # Contract Sizes (USD value per 1.00 lot)
  contract_sizes:
    # Major USD pairs
    EURUSD: 100000
    GBPUSD: 100000
    AUDUSD: 100000
    NZDUSD: 100000
    USDCAD: 100000
    USDCHF: 100000
    USDJPY: 100000
    USDSGD: 100000
    USDHKD: 100000
    USDNOK: 100000
    USDSEK: 100000
    USDDKK: 100000
    USDPLN: 100000
    USDZAR: 100000
    USDMXN: 100000
    
    # EUR cross pairs
    EURJPY: 100000
    EURGBP: 100000
    EURAUD: 100000
    EURNZD: 100000
    EURCAD: 100000
    EURCHF: 100000
    EURSGD: 100000
    EURNOK: 100000
    EURSEK: 100000
    EURDKK: 100000
    EURPLN: 100000
    EURZAR: 100000
    
    # GBP cross pairs
    GBPJPY: 100000
    GBPAUD: 100000
    GBPNZD: 100000
    GBPCAD: 100000
    GBPCHF: 100000
    GBPSGD: 100000
    GBPNOK: 100000
    GBPSEK: 100000
    GBPDKK: 100000
    GBPPLN: 100000
    GBPZAR: 100000
    
    # Other major cross pairs
    AUDJPY: 100000
    AUDCAD: 100000
    AUDCHF: 100000
    AUDNZD: 100000
    AUDSGD: 100000
    NZDJPY: 100000
    NZDCAD: 100000
    NZDCHF: 100000
    NZDSGD: 100000
    CADJPY: 100000
    CADCHF: 100000
    CADSGD: 100000
    CHFJPY: 100000
    CHFSGD: 100000
    SGDJPY: 100000
    
  # Lot Constraints (from broker)
  lot_constraints:
    min_lot: 0.01           # Minimum lot size
    max_lot: 100.0          # Maximum lot size  
    lot_step: 0.01          # Lot step increment
  
  # Entry Filters
  max_volatility: 80           # Max market volatility (0-100)
  min_correlation: 0.5         # Min correlation for recovery
  news_filter_minutes: 30      # Avoid trading X minutes around news
  
  # Profit Targets
  profit_levels:
    quick_scalp: 8             # First profit level (pips)
    partial_1: 15              # Second profit level (pips)
    partial_2: 25              # Third profit level (pips)
    final_target: 40           # Final profit target (pips)
  
  # Profit Taking Percentages
  profit_percentages:
    quick_scalp: 25            # % to close at first level
    partial_1: 25              # % to close at second level
    partial_2: 30              # % to close at third level
    final_target: 20           # % remaining at final level

# Recovery System Configuration
recovery:
  # Recovery Layers
  max_recovery_layers: 6       # Maximum recovery depth
  recovery_multiplier: 1.5     # Lot size multiplier for recovery
  
  # Correlation Thresholds
  strong_correlation: 0.8      # Strong correlation threshold
  medium_correlation: 0.6      # Medium correlation threshold
  weak_correlation: 0.4        # Weak correlation threshold
  
  # Recovery Timing
  recovery_delay: 30           # Seconds before activating recovery
  max_recovery_time: 14400     # Max recovery time (4 hours)
  
  # Recovery Filters
  max_drawdown_trigger: 15.0   # Activate recovery at X% drawdown
  correlation_stability: 0.3   # Min correlation stability required

# GUI Configuration
gui:
  # Window Settings
  window_title: "🔥 Arbi Phoenix Dashboard"
  window_width: 1400
  window_height: 900
  
  # Update Frequencies (milliseconds)
  portfolio_update: 1000       # Portfolio status update
  triangle_update: 500         # Triangle status update
  recovery_update: 2000        # Recovery status update
  chart_update: 5000           # Chart update frequency
  
  # Display Settings
  max_activity_lines: 100      # Max lines in activity feed
  decimal_places: 2            # Decimal places for display
  
  # Colors (hex codes)
  colors:
    profit: "#00FF00"          # Green for profits
    loss: "#FF0000"            # Red for losses
    neutral: "#FFFF00"         # Yellow for neutral
    background: "#1E1E1E"      # Dark background
    text: "#FFFFFF"            # White text

# Logging Configuration
logging:
  level: "INFO"                # DEBUG, INFO, WARNING, ERROR
  file_path: "data/logs/phoenix.log"
  max_file_size: "10MB"
  backup_count: 5
  
  # Log Categories
  categories:
    arbitrage: true            # Log arbitrage activities
    recovery: true             # Log recovery activities
    profit: true               # Log profit activities
    errors: true               # Log errors
    debug: false               # Log debug information

# Database Configuration
database:
  type: "sqlite"               # sqlite, postgresql
  path: "data/phoenix.db"
  
  # Tables to maintain
  tables:
    trades: true               # Trade history
    triangles: true            # Triangle performance
    recovery: true             # Recovery statistics
    correlations: true         # Correlation history
    performance: true          # Performance metrics

# Risk Management
risk_management:
  # Emergency Protocols
  max_daily_loss: 10.0         # Max daily loss (%)
  max_drawdown: 20.0           # Max total drawdown (%)
  
  # Triangle Balance Controls
  max_exposure_per_triangle: 30000  # Max $30K total per triangle
  max_imbalance_ratio: 1.5          # Max 1.5:1 ratio between legs
  rebalance_threshold: 0.10         # Rebalance if >10% imbalanced
  
  # Position Size Limits
  max_lot_per_pair: 10.0            # Max lot size per currency pair
  max_total_lots: 50.0              # Max total lots across all positions
  
  # Circuit Breakers
  volatility_circuit: 95       # Stop trading at extreme volatility
  correlation_circuit: 0.2     # Stop when correlations break down
  
  # Position Limits
  max_positions_per_pair: 3    # Max positions per currency pair
  max_total_positions: 50      # Max total open positions
  
  # Time Limits
  max_position_duration: 86400 # Max position duration (24 hours)
  trading_hours:
    start: "00:00"             # Trading start time (UTC)
    end: "23:59"               # Trading end time (UTC)
    
# Performance Monitoring
monitoring:
  # Metrics Collection
  collect_metrics: true
  metrics_interval: 60         # Seconds between metric collection
  
  # Performance Targets
  targets:
    daily_return: 5.0          # Target daily return (%)
    weekly_return: 25.0        # Target weekly return (%)
    monthly_return: 100.0      # Target monthly return (%)
    
  # Alerts
  alerts:
    email_enabled: false       # Enable email alerts
    sms_enabled: false         # Enable SMS alerts
    desktop_enabled: true      # Enable desktop notifications
    
# Advanced Features
advanced:
  # Machine Learning
  ml_enabled: false            # Enable ML predictions
  ml_model_path: "data/models/phoenix_ml.pkl"
  
  # Multi-threading
  max_threads: 8               # Max concurrent threads
  
  # Caching
  cache_enabled: true          # Enable data caching
  cache_size: 1000             # Max cache entries
  
  # Optimization
  optimize_enabled: true       # Enable parameter optimization
  optimization_interval: 3600  # Optimization interval (1 hour)
